try {
    console.log(a + b)
}
catch (err) {
    console.log("Syntax error")
}

console.log("Code still runs...")